import { ProjectType } from '@/types/project';

// Datos actualizados de los proyectos
const projects: ProjectType[] = [
  {
    id: '1',
    title: 'LA BODEGA',
    slug: 'Remodelación de bodega en desuso para crear salas de descanso y bienestar para conductores de transporte público.',
    coverImage: '/images/projects/LA BODEGA/project1 (17).png',
    images: [
      '/images/projects/LA BODEGA/project1 (1).png',
      '/images/projects/LA BODEGA/project1 (2).png',
      '/images/projects/LA BODEGA/project1 (3).png',
      '/images/projects/LA BODEGA/project1 (4).png',
      '/images/projects/LA BODEGA/project1 (5).png',
      '/images/projects/LA BODEGA/project1 (6).png',
      '/images/projects/LA BODEGA/project1 (7).png',
      '/images/projects/LA BODEGA/project1 (8).png',
      '/images/projects/LA BODEGA/project1 (9).png',
      '/images/projects/LA BODEGA/project1 (10).png',
      '/images/projects/LA BODEGA/project1 (11).png',
      '/images/projects/LA BODEGA/project1 (12).png',
      '/images/projects/LA BODEGA/project1 (13).png',
      '/images/projects/LA BODEGA/project1 (14).png',
      '/images/projects/LA BODEGA/project1 (15).png',
      '/images/projects/LA BODEGA/project1 (16).png',
      '/images/projects/LA BODEGA/project1 (17).png',
      '/images/projects/LA BODEGA/project1 (18).png',
      '/images/projects/LA BODEGA/project1 (19).png',
      '/images/projects/LA BODEGA/project1 (20).png',
      '/images/projects/LA BODEGA/project1 (21).png',
    ],
    category: 'Remodelación - Diseño',
    excerpt: 'Remodelación de bodega en desuso para crear salas de descanso y bienestar para conductores de transporte público.',
    description: 'Este proyecto consistió en la intervención y remodelación de una antigua bodega inutilizada, perteneciente a una terminal de transporte, con el objetivo de convertirla en un espacio funcional y digno para el descanso de los conductores. La intervención fue realizada en 2024 para la empresa Coopetran en Colombia.\nEl diseño contempló zonas de estar, espacios de espera cómodos y ambientes de bienestar básico, priorizando la ventilación, el confort térmico y la recuperación de una estructura antes deteriorada. Se integraron colores institucionales (azul y blanco) en la fachada para mantener coherencia visual con la identidad de la empresa, y se optimizó el acceso peatonal y señalización para mejorar la orientación de los usuarios.\nLa intervención le dio nueva vida a un espacio olvidado, fortaleciendo la infraestructura de soporte al personal operativo y aportando al bienestar laboral dentro del ecosistema del transporte.',
    client: 'Coopetran',
    location: 'Bogotá',
    year: 2024,
    completed: true,
  },
  {
    id: '2',
    title: 'LA TERMINAL',
    slug: 'Diseño interior de oficinas para Coopetran en una terminal de transporte, con enfoque en funcionalidad y calidez institucional.',
    coverImage: '/images/projects/LA TERMINAL/project2 (1).png',
    images: [
      '/images/projects/LA TERMINAL/project2 (1).png',
      '/images/projects/LA TERMINAL/project2 (2).png',
      '/images/projects/LA TERMINAL/project2 (3).png',
      '/images/projects/LA TERMINAL/project2 (4).png',
      '/images/projects/LA TERMINAL/project2 (5).png',
      '/images/projects/LA TERMINAL/project2 (6).png',
      '/images/projects/LA TERMINAL/project2 (7).png',
      '/images/projects/LA TERMINAL/project2 (8).png',
      '/images/projects/LA TERMINAL/project2 (9).png',
    ],
    category: 'Diseño',
    excerpt: 'Diseño interior de oficinas para Coopetran en una terminal de transporte, con enfoque en funcionalidad y calidez institucional.',
    description: 'Este proyecto corresponde al diseño interior de las oficinas de una terminal de transporte para Coopetran, una reconocida empresa colombiana del sector transporte. Realizado en 2024, el espacio fue pensado para optimizar la operatividad de atención al cliente y gestión interna, sin perder una atmósfera acogedora y profesional.\nSe empleó una paleta de materiales cálidos, como la madera natural, aplicada en listones verticales que funcionan tanto como elemento divisorio como recurso estético que unifica visualmente las diferentes zonas de trabajo. Las estaciones de escritorio fueron diseñadas en madera maciza con almacenamiento integrado, y el mobiliario selecciona fibras naturales para mantener una identidad cercana y humana, en contraste con la rigidez habitual de oficinas institucionales. La iluminación puntual y la integración de vegetación aportan un equilibrio visual y ambiental al entorno.\nEl resultado es una oficina contemporánea, eficiente y amable con el usuario, alineada con la identidad y valores de Coopetran.',
    client: 'Coopetran',
    location: 'Bogotá',
    year: 2024,
    completed: true,
  },

  {
    id: '4',
    title: 'NIDO',
    slug: 'Diseño de estudio para una trabajadora de una multinacional, que combina funcionalidad profesional con calidez residencial.',
    coverImage: '/images/projects/NIDO/project4 (1).jpg',
    images: [
      '/images/projects/NIDO/project4 (1).jpg',
      '/images/projects/NIDO/project4 (2).png',
      '/images/projects/NIDO/project4 (3).jpg',
      '/images/projects/NIDO/project4 (4).png',
    ],
    category: 'Remodelación - Diseño',
    excerpt: 'Diseño de estudio para una trabajadora de una multinacional, que combina funcionalidad profesional con calidez residencial.',
    description: 'Este proyecto corresponde al diseño y remodelación de un estudio para una trabajadora de una multinacional en Bogotá, Colombia. El objetivo fue crear un espacio de alto rendimiento que también ofreciera confort y una atmósfera cálida para el trabajo remoto y el descanso. Se diseñó un escritorio amplio en madera clara, bañado por luz natural gracias a su ubicación junto a la ventana. Una pared con listones de madera verticales sirve como fondo visual que aporta textura y orden al ambiente. El espacio se complementa con una zona de lectura o descanso en forma de banca/cama, y una estantería empotrada para libros, plantas y objetos personales. El diseño equilibra lo operativo y lo emocional, proponiendo un entorno sereno, moderno y acogedor que apoya la productividad sin sacrificar bienestar.',
    client: 'Conjunto Residencial Fuentes del Salitre',
    location: 'Bogotá',
    year: 2024,
    completed: true,
  },
  {
    id: '5',
    title: 'FUENTES SALITRE',
    slug: 'Remodelación de zona BBQ en espacio de descanso dentro de conjunto residencial.',
    coverImage: '/images/projects/FUENTES SALITRE/project5 (1).png',
    images: [
      '/images/projects/FUENTES SALITRE/project5 (1).png',
      '/images/projects/FUENTES SALITRE/project5 (2).png',
    ],
    category: 'Remodelación - Diseño',
    excerpt: 'Remodelación de zona BBQ en espacio de descanso dentro de conjunto residencial.',
    description: 'El proyecto consiste en la remodelación de un área previamente destinada para BBQ dentro de un conjunto residencial, transformándola en un espacio de descanso y encuentro para los residentes. Se incorporaron bancas de concreto con respaldos de madera, una fuente central de piedra que aporta frescura y sonido ambiental, pavimento en mosaico de piedra que delimita el área y jardineras perimetrales con vegetación tropical para generar privacidad y contacto con la naturaleza. El cerramiento metálico negro proporciona seguridad sin interrumpir la visual hacia el entorno verde. El diseño prioriza la comodidad, la estética contemporánea y la integración con el paisaje, creando un ambiente acogedor para los residentes.',
    client: 'Conjunto Residencial Fuentes del Salitre',
    location: 'Bogotá',
    year: 2024,
    completed: true,
  },
  {
    id: '6',
    title: 'WESTERN',
    slug: 'Diseño interior y renders para local de Western Union en Bogotá.',
    coverImage: '/images/projects/WESTERN/project6 (1).png',
    images: [
      '/images/projects/WESTERN/project6 (1).png',
      '/images/projects/WESTERN/project6 (2).png',
      '/images/projects/WESTERN/project6 (3).png',
      '/images/projects/WESTERN/project6 (4).png',
      '/images/projects/WESTERN/project6 (5).png',
    ],
    category: 'Diseño',
    excerpt: 'Diseño interior y renders para local de Western Union en Bogotá.',
    description: 'Este proyecto corresponde al diseño interior y generación de renders para un local de Western Union ubicado en Bogotá. El diseño busca reflejar una imagen moderna y alineada con la identidad corporativa de la marca, utilizando una paleta de colores vibrantes en amarillo y negro, materiales resistentes y detalles funcionales como ventanillas de atención, mobiliario compacto y espejos decorativos. El espacio optimiza la circulación y la experiencia del usuario, generando un ambiente eficiente y visualmente atractivo para las operaciones de envío y recepción de dinero.',
    client: 'Western Union',
    location: 'Bogotá',
    year: 2025,
    completed: true,
  },
  {
    id: '7',
    title: 'ITALIANO',
    slug: 'Diseño y remodelación de restaurante Trattoria di Luigi en Villeta.',
    coverImage: '/images/projects/ITALIANO/project7 (1).jpg',
    images: [
      '/images/projects/ITALIANO/project7 (1).jpeg',
      '/images/projects/ITALIANO/project7 (1).jpg',
      '/images/projects/ITALIANO/project7 (2).jpeg',
      '/images/projects/ITALIANO/project7 (2).jpg',
      '/images/projects/ITALIANO/project7 (3).jpeg',
      '/images/projects/ITALIANO/project7 (3).jpg',
      '/images/projects/ITALIANO/project7 (4).jpeg',
      '/images/projects/ITALIANO/project7 (4).jpg',
      '/images/projects/ITALIANO/project7 (5).jpg',
      '/images/projects/ITALIANO/project7 (6).jpg',
      '/images/projects/ITALIANO/project7 (7).jpg',
      '/images/projects/ITALIANO/project7 (8).jpg',
      '/images/projects/ITALIANO/project7 (9).jpg',
      '/images/projects/ITALIANO/project7 (10).jpg',
    ],
    category: 'Remodelación - Diseño',
    excerpt: 'Diseño y remodelación de restaurante Trattoria di Luigi en Villeta.',
    description: 'El proyecto abarca el diseño y la remodelación integral del restaurante Trattoria di Luigi, ubicado en Villeta. Se buscó renovar la imagen del local para crear un ambiente cálido y acogedor que reflejara la esencia italiana del lugar. Se incorporaron materiales como madera, mimbre y detalles de iluminación indirecta para generar atmósferas íntimas y sofisticadas. El mobiliario fue cuidadosamente seleccionado para optimizar la comodidad y la funcionalidad del espacio, mientras que el diseño del bar y las lámparas colgantes aportan un toque contemporáneo y artesanal. El resultado es un restaurante que combina tradición y modernidad, mejorando la experiencia del comensal.',
    client: 'Trattoria di Luigi',
    location: 'Villeta, Cundinamarca',
    year: 2025,
    completed: true,
  },
  {
    id: '8',
    title: 'SAMUELS ROOM',
    slug: 'Diseño de habitación infantil personalizada para Samuel.',
    coverImage: '/images/projects/SAMUELs ROOM/project8 (1).jpg',
    images: [
      '/images/projects/SAMUELs ROOM/project8 (1).jpg',
      '/images/projects/SAMUELs ROOM/project8 (2).jpg',
      '/images/projects/SAMUELs ROOM/project8 (3).jpg',
      '/images/projects/SAMUELs ROOM/project8 (4).jpg',
      '/images/projects/SAMUELs ROOM/project8 (5).jpg',
      '/images/projects/SAMUELs ROOM/project8 (6).jpg',
      '/images/projects/SAMUELs ROOM/project8 (7).jpg',
      '/images/projects/SAMUELs ROOM/project8 (8).jpg',
      '/images/projects/SAMUELs ROOM/project8 (9).jpg',
      '/images/projects/SAMUELs ROOM/project8 (10).jpg',
      '/images/projects/SAMUELs ROOM/project8 (11).jpg',
      '/images/projects/SAMUELs ROOM/project8 (12).jpg',
    ],
    category: 'Diseño',
    excerpt: 'Diseño de habitación infantil personalizada para Samuel.',
    description: 'Este proyecto consistió en el diseño de una habitación infantil para Samuel, hijo de un empresario que buscaba distintas propuestas para crear un espacio acogedor, funcional y lleno de calidez. El diseño integra tonos neutros, mobiliario en madera clara, y detalles personalizados como el nombre del niño en la cuna y elementos decorativos en forma de nube. Se priorizó el uso de materiales naturales y texturas suaves, incorporando una mecedora para los momentos de descanso y cuidado, y creando una atmósfera que promueve la tranquilidad, el juego y el vínculo familiar.',
    client: 'Particular (empresario, padre de Samuel)',
    location: 'Bogotá',
    year: 2025,
    completed: true,
  },
  {
    id: '9',
    title: 'SALON FUENTES SALITRE',
    slug: 'Propuesta de remodelación del salón social Fuentes del Salitre.',
    coverImage: '/images/projects/SALON FUENTES SALITRE/project9 (1).png',
    images: [
      '/images/projects/SALON FUENTES SALITRE/project9 (1).png',
      '/images/projects/SALON FUENTES SALITRE/project9 (2).png',
      '/images/projects/SALON FUENTES SALITRE/project9 (3).png',
      '/images/projects/SALON FUENTES SALITRE/project9 (4).png',
    ],
    category: 'Diseño',
    excerpt: 'Propuesta de remodelación del salón social Fuentes del Salitre.',
    description: 'Este proyecto fue una propuesta de diseño para la remodelación del salón social del conjunto Fuentes del Salitre en el año 2025. La propuesta se centró en modernizar el espacio utilizando materiales cálidos como la madera en techos y revestimientos, generando un ambiente acogedor y elegante. Se plantearon divisiones ligeras en madera tipo listonado para dar flexibilidad al espacio, mejorando su funcionalidad para eventos sociales, reuniones y actividades comunitarias, manteniendo al mismo tiempo una estética contemporánea y limpia.',
    client: 'Conjunto Residencial Fuentes del Salitre',
    location: 'Bogotá',
    year: 2025,
    completed: true,
  },
  {
    id: '10',
    title: 'TSURI',
    slug: 'Diseño del local Tsuri, especializado en comida asiática.',
    coverImage: '/images/projects/TSURI/project10 (1).jpg',
    images: [
      '/images/projects/TSURI/project10 (1).jpg',
      '/images/projects/TSURI/project10 (2).jpg',
      '/images/projects/TSURI/project10 (3).jpg',
      '/images/projects/TSURI/project10 (4).jpg',
      '/images/projects/TSURI/project10 (5).jpg',
      '/images/projects/TSURI/project10 (6).jpg',
      '/images/projects/TSURI/project10 (7).jpg',
      '/images/projects/TSURI/project10 (8).jpg',
      '/images/projects/TSURI/project10 (9).jpg',
      '/images/projects/TSURI/project10 (10).jpg',
      '/images/projects/TSURI/project10 (11).jpg',
      '/images/projects/TSURI/project10 (12).jpg',
    ],
    category: 'Diseño',
    excerpt: 'Diseño del local Tsuri, especializado en comida asiática.',
    description: 'Tsuri es un restaurante de comida asiática ubicado en Bogotá, diseñado en 2024 para un importante empresario del sector gastronómico. El concepto fusiona elementos tradicionales japoneses como faroles, paneles de madera y detalles gráficos con una estética moderna y minimalista. El espacio busca ofrecer una experiencia inmersiva de "Japanese street food", destacando materiales cálidos, iluminación de neón, vegetación integrada y un diseño funcional que optimiza tanto la barra como las mesas para brindar comodidad y estilo.',
    client: 'Empresario gastronómico',
    location: 'Winter Garden, Florida',
    year: 2024,
    completed: true,
  },
  {
    id: '11',
    title: 'STUDIO SHAPES',
    slug: 'Diseño de estudio para una pareja de empresarios en Bogotá.',
    coverImage: '/images/projects/STUDIO SHAPES/project11 (1).jpg',
    images: [
      '/images/projects/STUDIO SHAPES/project11 (1).jpg',
      '/images/projects/STUDIO SHAPES/project11 (2).jpg',
      '/images/projects/STUDIO SHAPES/project11 (3).jpg',
      '/images/projects/STUDIO SHAPES/project11 (4).jpg',
      '/images/projects/STUDIO SHAPES/project11 (5).jpg',
    ],
    category: 'Diseño',
    excerpt: 'Diseño de estudio para una pareja de empresarios en Bogotá.',
    description: 'Este proyecto consiste en el diseño de un estudio multifuncional en Bogotá para una pareja de empresarios, realizado en 2025. El espacio combina área de trabajo, ocio y descanso en un solo ambiente, optimizando cada rincón con mobiliario a medida, iluminación cálida y elementos tecnológicos como paneles LED decorativos y una pantalla de gran formato. El diseño integra materiales como madera clara, tonos neutros y detalles en negro para lograr un ambiente sofisticado, acogedor y altamente funcional.',
    client: 'Pareja de empresarios',
    location: 'Bogotá',
    year: 2024,
    completed: true,
  },
  {
    id: '12',
    title: 'FISIO DESK',
    slug: 'Diseño integral de mueble y habitación dentro de la remodelación de un consultorio de fisioterapia, con enfoque funcional y cálido.',
    coverImage: '/images/projects/FISIO DESK/project12 (1).jpg',
    images: [
      '/images/projects/FISIO DESK/project12 (1).jpg',
      '/images/projects/FISIO DESK/project12 (2).jpg',
      '/images/projects/FISIO DESK/project12 (3).jpg',
      '/images/projects/FISIO DESK/project12 (4).jpg',
      '/images/projects/FISIO DESK/project12 (5).jpg',
      '/images/projects/FISIO DESK/project12 (6).jpg',
      '/images/projects/FISIO DESK/project12 (7).jpg',
    ],
    category: 'Remodelación - Diseño',
    excerpt: 'Diseño integral de mueble y habitación dentro de la remodelación de un consultorio de fisioterapia, con enfoque funcional y cálido.',
    description: 'Este proyecto forma parte de la remodelación de un espacio para una fisioterapeuta en Bogotá, buscando integrar un área privada con un ambiente funcional y sereno. Se diseñó un mueble a medida que resuelve necesidades de escritorio, almacenamiento y exhibición en una sola estructura compacta. El mobiliario, realizado en madera de acabado cálido, armoniza con el entorno y aporta calidez al espacio. La iluminación natural y la disposición estratégica de libros, plantas y objetos personales refuerzan la atmósfera terapéutica y acogedora, ideal tanto para el descanso como para el trabajo. Cada elemento fue pensado para optimizar el uso del espacio sin perder confort ni estética.',
    client: 'Fisioterapeuta (privado)',
    location: 'Bogotá',
    year: 2025,
    completed: true,
  },
  {
    id: '13',
    title: 'BAÑO FISIO',
    slug: 'Baño renovado con estética minimalista y detalles funcionales.',
    coverImage: '/images/projects/BAÑO FISIO/project13 (1).jpg',
    images: [
      '/images/projects/BAÑO FISIO/project13 (1).jpg',
      '/images/projects/BAÑO FISIO/project13 (2).jpg',
      '/images/projects/BAÑO FISIO/project13 (3).jpg',
    ],
    category: 'Diseño',
    excerpt: 'Baño renovado con estética minimalista y detalles funcionales.',
    description: 'Este proyecto consistió en la remodelación integral de un baño en una vivienda particular en Bogotá, perteneciente a una fisioterapeuta. El diseño se centró en crear un espacio que combinara funcionalidad con una estética serena y contemporánea. Se emplearon materiales de fácil mantenimiento y tonalidades neutras para transmitir limpieza y amplitud. El mobiliario fue diseñado a medida para optimizar el almacenamiento sin saturar el espacio, incorporando elementos en madera natural que aportan calidez. La iluminación, tanto natural como artificial, fue cuidadosamente planificada para resaltar los acabados y crear un ambiente acogedor. El resultado es un baño que responde a las necesidades prácticas de la usuaria, al tiempo que ofrece un entorno relajante y armonioso.',
    client: 'Fisioterapeuta (privado)',
    location: 'Bogotá',
    year: 2025,
    completed: true,
  },
];

// Funciones para obtener datos
export async function getAllProjects(): Promise<ProjectType[]> {
  // Aquí conectarías con tu API/CMS en producción
  return projects;
}

export async function getProjectBySlug(slug: string): Promise<ProjectType | null> {
  // Aquí conectarías con tu API/CMS en producción
  const project = projects.find(p => p.slug === slug);
  return project || null;
}

export async function getProjectsByCategory(category: string): Promise<ProjectType[]> {
  // Aquí conectarías con tu API/CMS en producción
  return projects.filter(p => p.category === category);
}